### ISSUE TITLE
Request for 'grouped options' support for 'select' component

### ISSUE THREAD

**Issue by ChrisBAshton** [alphagov/govuk_publishing_components#4696]
Whitehall's [select_with_search](https://github.com/alphagov/whitehall/blob/50b8ddd41e0d1d12ba5d27dc7ac9e9b7f37a5f2a/app/views/components/docs/select_with_search.yml#L46) component is a bespoke component that wraps around the 'select' component. It adds a search input field, to make the options searchable (powered by Choices.js).

In addition, it supports `<optgroup>` via a `grouped_options` property, where instead of:

```yml
      options:
      - text: Option one
        value: option1
      - text: Option two
        value: option2
```

We have data like:

```yml
      grouped_options:
      - - England
        - - text: Bath
            value: bath
          - text: Bristol
            value: bristol
          - text: London
            value: london
          - text: Manchester
            value: manchester
      - - Northern Ireland
        - - text: Bangor
            value: bangor
          - text: Belfast
            value: belfast
```

Screenshot example:

> ![Image](https://github.com/user-attachments/assets/20eaa635-ba4e-43c1-9e09-9ed46be8d082)

This is a genuinely useful feature which doesn't need to be coupled to 'select with search' - it could be supported by the 'select' component itself with minimal tweaks.

The 'search' component's lack of support for this was ultimately a factor in [deciding which component to go with](https://trello.com/c/pmbL2yId/3411-consolidate-the-autocomplete-selectwithsearch-components-in-whitehall) when we recently consolidated several similarly behaving components. We could potentially have explored killing off some of these more complex components if we were able to fall back on native 'grouped options' support from the standard Select component.
